apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: hello
  ports:
    - port: 80
      targetPort: 80
      NodePort: 30004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      name: my-app-pod
      labels:
        app: hello 
    spec:
      containers:
        - name: hello
          image: mdyasin5/pyimage
          ports: 
            - containerPort: 80            
          imagePullPolicy: Always
